### PR TITLE
✨ React admin integration

### LINKED ISSUE #50: Create user model to map users

### LINKED ISSUE #51: Register user via admin panel

### LINKED ISSUE #170: Redirect after creating an account
After successful creating new account website should move back to users list.

### LINKED ISSUE #171: Unable to delete user in admin panel
obraz

### LINKED ISSUE #204: Add user type to the login response
In react-admin, you can login as a user but you will not get any data. We have to get the user type to decide if our user should enter this website.

### PR DESCRIPTION
**Pull request by Kuboczoch**
- [x] Login to react-admin
- [x] Manage users
- - [x] Create user
- - [x] Delete user
- - [x] Edit user
- - [x] List users
- [x] Github action for react-admin
- [x] User type on login to decide if user is an admin #204

### CODE REVIEW

**Comment by Kuboczoch** [comment]
Issue #159 is required for this pr

**Comment by Kuboczoch** [comment]
Is it everything that we need? @HubertBalcerzak

**Comment by HubertBalcerzak** [comment]
blocked by #198

**Comment by HubertBalcerzak** [comment]
blocked by #207

**Pull request closed without merging**
