### PR TITLE
✨Error handling

### PR DESCRIPTION
**Pull request by HubertBalcerzak**

### CODE REVIEW

**Comment by HubertBalcerzak** [comment]
@Kuboczoch Frontend needs to be adapted to these changes and present error pages

**Comment by Kuboczoch** [comment]
> @Kuboczoch Frontend needs to be adapted to these changes and present error pages

@HubertBalcerzak Cool, I will add it in #202

**Comment by Kuboczoch** [comment]
@HubertBalcerzak On the other hand it will be very easy to implement it.

**Comment by Kuboczoch** [comment]
@HubertBalcerzak We have now /404 /403 /500 and /error page

**Pull request closed without merging**
